version: '3.1'

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - ./docker/db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
